In [1]:
import numpy as np

In [3]:
def divided_difference_table(x,y):
    n = len(x)
    table = np.zeros((n,n))
    table[:,0] = y
    for j in range(1,n):
        for i in range(n, -j):
            table[i,j] = (
            table[i + 1, j - 1] - table[i, j - 1]
            ) / (x[i + j] - x[i])
    return table

In [14]:
def newton_coefficients(table):
    return table[0,:]

In [15]:
def newton_interpolation(x_data,coefficients, x):
    n = len(coefficients)
    result = coefficients[n - 1]
    for i in range(n-2, -1, -1):
        result = coefficients[i] + (x - x_data[i]) * result
    return result

In [16]:
x = np.array([-2,-1,0,1,2], dtype=float)
y = x**2 + 2*x + 1

In [17]:
table = divided_difference_table(x,y)

In [18]:
coefficients = newton_coefficients(table)

In [19]:
print("Divided difference table:")
print(table)

Divided difference table:
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]
 [9. 0. 0. 0. 0.]]


In [20]:
print("Newton Coefficients:")
print(coefficients)

Newton Coefficients:
[1. 0. 0. 0. 0.]


In [21]:
evaluation_points = np.array([-1.5, 0.5,0.5,1.5])

In [22]:
print("\nEvaluation Results:")
print("x\t\tP4(x)\t\tf(x)\t\tAbsolute Error")

for point in evaluation_points:

    p_value = newton_interpolation(
        x,
        coefficients,
        point
    )

    exact_value = point**2 + 2*point + 1

    error = abs(exact_value - p_value)

    print(
        f"{point:.1f}\t\t"
        f"{p_value:.10f}\t"
        f"{exact_value:.10f}\t"
        f"{error:.10e}"
    )


Evaluation Results:
x		P4(x)		f(x)		Absolute Error
-1.5		1.0000000000	0.2500000000	7.5000000000e-01
0.5		1.0000000000	2.2500000000	1.2500000000e+00
0.5		1.0000000000	2.2500000000	1.2500000000e+00
1.5		1.0000000000	6.2500000000	5.2500000000e+00


In [23]:
import numpy as np

def divided_difference_table(x, y):

    n = len(x)

    # Create an n x n table filled with zeros
    table = np.zeros((n, n))

    # Zeroth-order divided differences = function values
    table[:, 0] = y

    # Calculate higher-order divided differences
    for j in range(1, n):
        for i in range(n - j):

            table[i, j] = (
                table[i + 1, j - 1] - table[i, j - 1]
            ) / (x[i + j] - x[i])

    return table


# ---------------------------------------------------------
# Extract Newton coefficients
# ---------------------------------------------------------
def newton_coefficients(table):

    # First element of every divided-difference column
    return table[0, :]


# ---------------------------------------------------------
# Evaluate Newton interpolation polynomial
# ---------------------------------------------------------
def newton_interpolation(x_data, coefficients, x):

    n = len(coefficients)

    # Start with the highest-order coefficient
    result = coefficients[n - 1]

    # Evaluate using nested multiplication
    for i in range(n - 2, -1, -1):

        result = coefficients[i] + (x - x_data[i]) * result

    return result


# ---------------------------------------------------------
# Q1
# ---------------------------------------------------------

# Data points
x = np.array([-2, -1, 0, 1, 2], dtype=float)

# Function values
y = x**2 + 2*x + 1


# Construct divided-difference table
table = divided_difference_table(x, y)


# Extract Newton coefficients
coefficients = newton_coefficients(table)


# ---------------------------------------------------------
# Display divided-difference table
# ---------------------------------------------------------

print("Divided-Difference Table:")
print(table)


# ---------------------------------------------------------
# Display Newton coefficients
# ---------------------------------------------------------

print("\nNewton Coefficients:")
print(coefficients)


# ---------------------------------------------------------
# Evaluate polynomial at required points
# ---------------------------------------------------------

evaluation_points = np.array([
    -1.5,
    -0.5,
     0.5,
     1.5
])

print("\nEvaluation Results:")
print("x\t\tP4(x)\t\tf(x)\t\tAbsolute Error")

for point in evaluation_points:

    p_value = newton_interpolation(
        x,
        coefficients,
        point
    )

    exact_value = point**2 + 2*point + 1

    error = abs(exact_value - p_value)

    print(
        f"{point:.1f}\t\t"
        f"{p_value:.10f}\t"
        f"{exact_value:.10f}\t"
        f"{error:.10e}"
    )

Divided-Difference Table:
[[ 1. -1.  1.  0.  0.]
 [ 0.  1.  1.  0.  0.]
 [ 1.  3.  1.  0.  0.]
 [ 4.  5.  0.  0.  0.]
 [ 9.  0.  0.  0.  0.]]

Newton Coefficients:
[ 1. -1.  1.  0.  0.]

Evaluation Results:
x		P4(x)		f(x)		Absolute Error
-1.5		0.2500000000	0.2500000000	0.0000000000e+00
-0.5		0.2500000000	0.2500000000	0.0000000000e+00
0.5		2.2500000000	2.2500000000	0.0000000000e+00
1.5		6.2500000000	6.2500000000	0.0000000000e+00
